# Site information
title: Nick's Blog
email: nick.beenham@gmail.com
description: Some random chap's ramblings.
baseurl: ""
url: "https://nickbeenham.dev"

# Site settings
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
date_format: "%b %-d, %Y"

google_analytics: G-DB167LBMFC

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap